# Tolerations to use for the Velero deployment. Optional.
tolerations:
  - key: ${toleration_key}
    value: ${toleration_value}
    effect: "NoSchedule"

kubectl:
  image:
    repository: docker.io/bitnami/kubectl
    # Digest value example: sha256:d238835e151cec91c6a811fe3a89a66d3231d9f64d09e5f3c49552672d271f38.
    # If used, it will take precedence over the kubectl.image.tag.
    # digest:
    # kubectl image tag. If used, it will take precedence over the cluster Kubernetes version.
    # tag: 1.16.15
##
## Parameters for the `default` BackupStorageLocation and VolumeSnapshotLocation,
## and additional server settings.
##
configuration:
  # Parameters for the BackupStorageLocation(s). Configure multiple by adding other element(s) to the backupStorageLocation slice.
  # See https://velero.io/docs/v1.6/api-types/backupstoragelocation/
  backupStorageLocation:
    # name is the name of the backup storage location where backups should be stored. If a name is not provided,
    # a backup storage location will be created with the name "default". Optional.
    - name: ${cloud_bucket_folder_name}
      # provider is the name for the backup storage location provider.
      provider: ${cloud_provider}
      # bucket is the name of the bucket to store backups in. Required.
      bucket: ${cloud_bucket}
      # prefix is the directory under which all Velero data should be stored within the bucket. Optional.
      prefix: ${cloud_bucket_prefix}
      # Additional provider-specific configuration. See link above
      # for details of required/optional fields for your provider.
      config:
        region: ${cloud_region}

  # Parameters for the VolumeSnapshotLocation(s). Configure multiple by adding other element(s) to the volumeSnapshotLocation slice.
  # See https://velero.io/docs/v1.6/api-types/volumesnapshotlocation/
  volumeSnapshotLocation:
    # name is the name of the volume snapshot location where snapshots are being taken. Required.
    - name: ${cloud_bucket_folder_name}
      # backupSyncPeriod: 1m
      # provider is the name for the volume snapshot provider.
      provider: ${cloud_provider}
      config:
        region: ${cloud_region}
  # additional key/value pairs to be used as environment variables such as "AWS_CLUSTER_NAME: 'yourcluster.domain.tld'"
  extraEnvVars:
    AWS_CLUSTER_NAME: ${cloud_bucket_prefix}

# Information about the Kubernetes service account Velero uses.
serviceAccount:
  server:
    create: true
    name: ${cloud_irsa_name}
    annotations:
      eks.amazonaws.com/role-arn: ${cloud_irsa_arn}

# Whether to deploy the node-agent daemonset.
deployNodeAgent: true
nodeAgent:
  # Tolerations to use for the node-agent daemonset. Optional.
  tolerations:
    - key: ${toleration_key}
      value: ${toleration_value}
      effect: "NoSchedule"

schedules:
  continuous:
    disabled: false
    schedule: "*/15 * * * *"
    useOwnerReferencesInBackup: false
    template:
      ttl: 168h
      includeClusterResources: true
      excludedNamespaces:
        - metrics-server
        - external-secrets
        - kube-node-lease
        - kube-public
        - kube-system

          # - aws-load-balancer
          # - cert-manager
          # - datadog
          # - default
          # - external-dns
          # - external-secrets
          # - kube-node-lease
          # - kube-public
          # - kube-state-metrics
          # - kube-system
          # - kyverno
          # - metrics-server
          # - splunk
          # - velero
  frequent:
    disabled: false
    schedule: "0 */8 * * *"
    useOwnerReferencesInBackup: false
    template:
      ttl: 168h
      includeClusterResources: true
      excludedNamespaces:
        - metrics-server
        - external-secrets
        - kube-node-lease
        - kube-public
        - kube-system
          # - aws-load-balancer
          # - cert-manager
          # - datadog
          # - default
          # - external-dns
          # - external-secrets
          # - kube-node-lease
          # - kube-public
          # - kube-state-metrics
          # - kube-system
          # - kyverno
          # - metrics-server
          # - splunk
          # - velero
  longterm:
    disabled: false
    schedule: "0 1 * * *"
    useOwnerReferencesInBackup: false
    template:
      ttl: 2190h
      includeClusterResources: true
      excludedNamespaces:
        - metrics-server
        - external-secrets
        - kube-node-lease
        - kube-public
        - kube-system
          # - aws-load-balancer
          # - cert-manager
          # - charter-system
          # - datadog
          # - default
          # - external-dns
          # - external-secrets
          # - kube-node-lease
          # - kube-public
          # - kube-state-metrics
          # - kube-system
          # - kyverno
          # - metrics-server
          # - splunk
          # - velero

metrics:
  enabled: true
